services:
  # This is the name of your application service (you could call it api, app, or anything you like).
  web:
    # Tells Docker Compose how to create the Docker image for this service. 
    # The period (.) means "look in the current directory" for the Dockerfile. 
    build: .
    # 3000 (Host Port): The port on your local machine you will visit.
    # 3000 (Container Port): The port the application inside the container is listening
    ports:
      - "3000:3000"
    # Specification of the environment file
    env_file:
      - .env
    # Sets up persistent data or syncs files between your host machine and the container.
    volumes:
      - .:/app # It syncs the entire current project directory to inside of the container.
      - /app/node_modules
    environment: 
      - NODE_ENV=development # production is another mode
    #  Sets the policy for when the container should automatically restart.
    restart: unless-stopped